name: build container

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/dergeberl/multitool:main
    - name: Login to ghcr.io
      run:  echo ${{ secrets.REGISTRY }} | docker login ghcr.io --username dergeberl --password-stdin
    - name: push image
      run: docker ghcr.io/dergeberl/multitool:main
